language: node_js
node_js:
  - "10"
  - "node"
env:
  global:
    - POSTGRES_PREFIX=/usr/lib/postgresql/10/bin/
    - CXX=g++-4.8
addons:
  postgres: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
      - postgresql-contrib-10
      - g++-4.8
    sources:
      - ubuntu-toolchain-r-test
